source 'https://rubygems.org'

gem 'rails', '3.2.9'
gem 'rails-api'
gem "active_model_serializers", github: "rails-api/active_model_serializers"

gem 'sqlite3'

gem 'blog',       path: '../blog'
gem 'blog_admin', path: '../blog_admin'

gem 'devise'
# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test, :development do
  gem "rspec-rails", "~> 2.0"
end
